version: '3'

networks:
  development:
  production:
services:
  # development
  account-development:
    networks:
      - development
    build:
      context: ./services/account
    dns: 10.0.0.2
    links:
      - vault-development
    environment:
      - VAULT_ADDR=http://vault-development:8200
      - VAULT_USERNAME=account-development
      - VAULT_PASSWORD=123-account-development
    restart: on-failure
  gateway-development:
    networks:
      - development
    build:
      context: ./services/gateway
    dns: 10.0.0.2
    links:
      - vault-development
    environment:
      - VAULT_ADDR=http://vault-development:8200
      - VAULT_USERNAME=gateway-development
      - VAULT_PASSWORD=123-gateway-development
    restart: on-failure
  payment-development:
    networks:
      - development
    build:
      context: ./services/payment
    dns: 10.0.0.2
    links:
      - vault-development
    environment:
      - VAULT_ADDR=http://vault-development:8200
      - VAULT_USERNAME=payment-development
      - VAULT_PASSWORD=123-payment-development
    restart: on-failure

  vault-development:
    networks:
      - development
    image: vault:1.8.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=f23612cf-824d-4206-9e94-e31a6dc8ee8d
    # production    
  vault-production:
    networks:
      - production
    image: vault:1.8.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8301:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=083672fc-4471-4ec4-9b59-a285e463a973
  account-production:
    networks:
      - production
    build:
      context: ./services/account
    dns: 10.0.0.2
    links:
      - vault-production
    environment:
      - VAULT_ADDR=http://vault-production:8200
      - VAULT_USERNAME=account-production
      - VAULT_PASSWORD=123-account-production
    restart: on-failure
  gateway-production:
    networks:
      - production
    build:
      context: ./services/gateway
    dns: 10.0.0.2
    links:
      - vault-production
    environment:
      - VAULT_ADDR=http://vault-production:8200
      - VAULT_USERNAME=gateway-production
      - VAULT_PASSWORD=123-gateway-production
    restart: on-failure
  payment-production:
    networks:
      - production
    build:
      context: ./services/payment
    dns: 10.0.0.2
    links:
      - vault-production
    environment:
      - VAULT_ADDR=http://vault-production:8200
      - VAULT_USERNAME=payment-production
      - VAULT_PASSWORD=123-payment-production
    restart: on-failure       

